name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - id: "setup-node"
        uses: "actions/setup-node@v2"
        with:
          node-version: 18.x

      - id: "install"
        run: yarn install --frozen-lockfile

      - id: "build"
        run: yarn build

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v1"
        with:
          name: "iftttToNotion"
          runtime: "nodejs18"
          region: "asia-northeast1"
          env_vars: "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }},NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}"

      - id: "health-check"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
